apiVersion: v1
kind: Service
metadata:
  name: flip-flop
spec:
  selector:
    app: flip-flop
  ports:
  - protocol: "TCP"
    port: 8000
    targetPort: 8000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flip-flop
spec:
  selector:
    matchLabels:
      app: flip-flop
  replicas: 1
  template:
    metadata:
      labels:
        app: flip-flop
    spec:
      containers:
      - name: flask
        image: docker.io/library/flip-flop:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        startupProbe:
          httpGet:
            path: /healthcheck
            port: 8000
            scheme: HTTP
